project:
  type: website

website:
  title: "ISSS622-GAA"
  navbar:
    left:
    - text : "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/hands-on_ex01/hands-on_ex01.html"
    - text : "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 1"
          href: "In_class_Ex/In_Class_Ex01/In_Class_Ex01.html"
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

