<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dew Stella Chan">
<meta name="dcterms.date" content="2024-09-27">

<title>Take-Home Exercise 2 – ISSS622-GAA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS622-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex01/hands-on_ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex02/hands-on_ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex03/hands-on_ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex04/hands-on_ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex05/hands-on_ex05.html">
 <span class="dropdown-text">Hands-on Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex06/hands-on_ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/hands-on_ex07/hands-on_ex07.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In_Class_Ex/In_Class_Ex01/In_Class_Ex01.html">
 <span class="dropdown-text">In Class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_Ex/In_Class_Ex03/In_Class_Ex03.html">
 <span class="dropdown-text">In Class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_Ex/In_Class_Ex04/In_Class_Ex04.html">
 <span class="dropdown-text">In Class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_Ex/In_Class_Ex05/In_Class_Ex05.html">
 <span class="dropdown-text">In Class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_Ex/In_Class_Ex06/In_Class_Ex06.html">
 <span class="dropdown-text">In Class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In_Class_Ex/In_Class_Ex07/In_Class_Ex06.html">
 <span class="dropdown-text">In Class Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take_home_Ex/Take_home_01/Take_home_01.html">
 <span class="dropdown-text">Take Home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take_home_Ex/Take_home_02/Take_home_02.html">
 <span class="dropdown-text">Take Home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#loading-of-libraries" id="toc-loading-of-libraries" class="nav-link active" data-scroll-target="#loading-of-libraries">Loading of Libraries</a></li>
  <li><a href="#data-preparation-and-transformation" id="toc-data-preparation-and-transformation" class="nav-link" data-scroll-target="#data-preparation-and-transformation">Data preparation and Transformation</a>
  <ul class="collapse">
  <li><a href="#loading-of-thailand---subnational-administrative-boundaries" id="toc-loading-of-thailand---subnational-administrative-boundaries" class="nav-link" data-scroll-target="#loading-of-thailand---subnational-administrative-boundaries">Loading of Thailand - Subnational Administrative Boundaries</a></li>
  <li><a href="#loading-and-preparation-of-thailand-tourism-statistics" id="toc-loading-and-preparation-of-thailand-tourism-statistics" class="nav-link" data-scroll-target="#loading-and-preparation-of-thailand-tourism-statistics">Loading and preparation of Thailand Tourism Statistics</a></li>
  <li><a href="#to-derive-foreign-tourists-related-spending-indicators-for-the-study-period." id="toc-to-derive-foreign-tourists-related-spending-indicators-for-the-study-period." class="nav-link" data-scroll-target="#to-derive-foreign-tourists-related-spending-indicators-for-the-study-period.">To derive foreign tourists related spending indicators for the study period.</a></li>
  </ul></li>
  <li><a href="#visualising-foreign-tourists-indicators-for-year-2019-to-2023" id="toc-visualising-foreign-tourists-indicators-for-year-2019-to-2023" class="nav-link" data-scroll-target="#visualising-foreign-tourists-indicators-for-year-2019-to-2023">Visualising Foreign Tourists Indicators for year 2019 to 2023</a>
  <ul class="collapse">
  <li><a href="#amount-of-revenue-per-foreign-tourist" id="toc-amount-of-revenue-per-foreign-tourist" class="nav-link" data-scroll-target="#amount-of-revenue-per-foreign-tourist">Amount of Revenue per Foreign Tourist</a></li>
  </ul></li>
  <li><a href="#analyising-if-tourist-hotspot-is-related-to-space" id="toc-analyising-if-tourist-hotspot-is-related-to-space" class="nav-link" data-scroll-target="#analyising-if-tourist-hotspot-is-related-to-space">Analyising if Tourist hotspot is related to space</a></li>
  <li><a href="#exploratory-spatial-data-analysis" id="toc-exploratory-spatial-data-analysis" class="nav-link" data-scroll-target="#exploratory-spatial-data-analysis">Exploratory Spatial Data Analysis:</a>
  <ul class="collapse">
  <li><a href="#fixed-distance-weight-matrix" id="toc-fixed-distance-weight-matrix" class="nav-link" data-scroll-target="#fixed-distance-weight-matrix">Fixed Distance weight Matrix</a></li>
  <li><a href="#adaptive-distanace-weight-matrix" id="toc-adaptive-distanace-weight-matrix" class="nav-link" data-scroll-target="#adaptive-distanace-weight-matrix">Adaptive Distanace weight matrix</a></li>
  <li><a href="#plotting-adaptive-distance-based-neighbours" id="toc-plotting-adaptive-distance-based-neighbours" class="nav-link" data-scroll-target="#plotting-adaptive-distance-based-neighbours">Plotting Adaptive Distance-based Neighbours</a></li>
  <li><a href="#row-standardised-weights-martix" id="toc-row-standardised-weights-martix" class="nav-link" data-scroll-target="#row-standardised-weights-martix">Row-Standardised Weights martix</a></li>
  </ul></li>
  <li><a href="#spatial-lag-with-row-standardized-weights" id="toc-spatial-lag-with-row-standardized-weights" class="nav-link" data-scroll-target="#spatial-lag-with-row-standardized-weights">Spatial lag with row-standardized weights</a>
  <ul class="collapse">
  <li><a href="#computing-global-moran-i" id="toc-computing-global-moran-i" class="nav-link" data-scroll-target="#computing-global-moran-i">Computing Global Moran’ I</a></li>
  <li><a href="#gearys-c-test" id="toc-gearys-c-test" class="nav-link" data-scroll-target="#gearys-c-test">Geary’s C Test</a></li>
  <li><a href="#computing-local-morans-i" id="toc-computing-local-morans-i" class="nav-link" data-scroll-target="#computing-local-morans-i">Computing local Moran’s I</a></li>
  <li><a href="#lisa-map" id="toc-lisa-map" class="nav-link" data-scroll-target="#lisa-map">Lisa Map:</a></li>
  </ul></li>
  <li><a href="#hot-spot-area-analysis" id="toc-hot-spot-area-analysis" class="nav-link" data-scroll-target="#hot-spot-area-analysis">Hot Spot Area Analysis</a></li>
  <li><a href="#gi-statistics-using-fixed-distance" id="toc-gi-statistics-using-fixed-distance" class="nav-link" data-scroll-target="#gi-statistics-using-fixed-distance">Gi statistics using fixed distance</a></li>
  <li><a href="#time-series" id="toc-time-series" class="nav-link" data-scroll-target="#time-series">Time Series</a>
  <ul class="collapse">
  <li><a href="#emerging-hotpots" id="toc-emerging-hotpots" class="nav-link" data-scroll-target="#emerging-hotpots">Emerging Hotpots</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions:</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home Exercise 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dew Stella Chan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 27, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 13, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<p>This page documents the codes and the analysis performed for Take Home Exercise 02.</p>
<p>The objectives of this exercise is to discover:</p>
<ul>
<li><p>If the key indicators of tourism economy of Thailand are independent from space and space and time.</p></li>
<li><p>If the tourism economy is indeed spatial and spatio-temporal dependent, then, you would like to detect where are the clusters and outliers, and the emerging hot spot/cold spot areas.</p></li>
</ul>
<p>Since tourism data used in this assignment covers, Pre, During and Post COVID-19 Pandemic period, the focus of this assignments will be on the foreign tourists related indicators from 2019 to 2023.</p>
<section id="loading-of-libraries" class="level2">
<h2 class="anchored" data-anchor-id="loading-of-libraries">Loading of Libraries</h2>
<p>Due to the exploration of Geo spatial techniques, more packages were loaded to facilitates the different techniques used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, sp, sfdep, raster, spatstat, tmap, tidyverse, lubridate, readxl, spNetwork, plotly, tidyverse, Kendall,  knitr, spdep, patchwork)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>) <span class="co">#set seed to ensure the result is consistent</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-preparation-and-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation-and-transformation">Data preparation and Transformation</h2>
<section id="loading-of-thailand---subnational-administrative-boundaries" class="level3">
<h3 class="anchored" data-anchor-id="loading-of-thailand---subnational-administrative-boundaries">Loading of Thailand - Subnational Administrative Boundaries</h3>
<p>This assignment focuses on the analysis of tourism related on foreigners indicators on Province level of the Kingdom of Thailand.</p>
<p>The <a href="https://data.humdata.org/dataset/cod-ab-tha?">Thailand - Subnational Administrative Boundaries</a> at HDX is used for the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#|eval: false</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>SAB_1 <span class="ot">=</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data"</span>, <span class="at">layer =</span> <span class="st">"tha_admbnda_adm1_rtsd_20220121"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tha_admbnda_adm1_rtsd_20220121' from data source 
  `C:\dewschan\ISSS622-GAA\Take_home_Ex\Take_home_02\data' using driver `ESRI Shapefile'
Simple feature collection with 77 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<section id="writing-and-reading-the-province-data-to-rds-folder" class="level4">
<h4 class="anchored" data-anchor-id="writing-and-reading-the-province-data-to-rds-folder">Writing and Reading the Province data to rds folder</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(SAB_1,<span class="st">"data/rds/SAB_1.rds"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#to save the file to rds</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#re-reading the acc file to the environments</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>SAB_1<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/SAB_1.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="loading-and-preparation-of-thailand-tourism-statistics" class="level3">
<h3 class="anchored" data-anchor-id="loading-and-preparation-of-thailand-tourism-statistics">Loading and preparation of Thailand Tourism Statistics</h3>
<p>The <a href="https://www.kaggle.com/datasets/thaweewatboy/thailand-domestic-tourism-statistics">Thailand Domestic Tourism Statistics</a> at Kaggle is used for this analysis. This section show the code for data preparation and transformation of theThailand Toursim Statistics.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Tour_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/thailand_domestic_tourism_2019_2023_ver2.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Standardizing the Province Names with the Thailand Subnational Administrative Boundaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Tour_data <span class="ot">&lt;-</span> Tour_data <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">province_eng =</span> <span class="fu">case_when</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Buriram"</span> <span class="sc">~</span> <span class="st">"Buri Ram"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Chainat"</span> <span class="sc">~</span> <span class="st">"Chai Nat"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Chonburi"</span> <span class="sc">~</span> <span class="st">"Chon Buri"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Lopburi"</span> <span class="sc">~</span> <span class="st">"Lop Buri"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Nong Bua Lamphu"</span> <span class="sc">~</span> <span class="st">"Nong Bua Lam Phu"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Phang Nga"</span> <span class="sc">~</span> <span class="st">"Phangnga"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Prachinburi"</span> <span class="sc">~</span> <span class="st">"Prachin Buri"</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    province_eng <span class="sc">==</span> <span class="st">"Sisaket"</span> <span class="sc">~</span> <span class="st">"Si Sa Ket"</span>,</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> province_eng</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>Tour_data <span class="ot">&lt;-</span><span class="fu">rename</span>(Tour_data, <span class="at">ADM1_EN =</span> province_eng, <span class="at">Date_tour =</span> date )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="writing-and-reading-the-data-in-tourism-statistics-to-rds-folder" class="level5">
<h5 class="anchored" data-anchor-id="writing-and-reading-the-data-in-tourism-statistics-to-rds-folder">Writing and Reading the data in Tourism Statistics to rds folder</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(Tour_data,<span class="st">"data/rds/Tour_data.rds"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#to save the file to rds</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Tour_data<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/Tour_data.rds"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#re-reading the acc file to the environments</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-transformation" class="level4">
<h4 class="anchored" data-anchor-id="data-transformation">Data Transformation</h4>
<p>Transform tour data from long table into a table with the 8 different indicators in the variables column into individual column for data analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tour_data_wide <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(Tour_data, <span class="at">names_from =</span> <span class="st">"variable"</span>, <span class="at">values_from =</span> <span class="st">"value"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(tour_data_wide,<span class="st">"data/rds/tour_data_wide.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="reading-the-wide-data-in-tourism-statistics-from-rds-folder" class="level5">
<h5 class="anchored" data-anchor-id="reading-the-wide-data-in-tourism-statistics-from-rds-folder">Reading the wide data in Tourism Statistics from rds folder:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">#re-reading the acc file to the environments</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tour_data_wide<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/tour_data_wide.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="joining-the-aspatial-long-data-to-geospatial-data" class="level4">
<h4 class="anchored" data-anchor-id="joining-the-aspatial-long-data-to-geospatial-data">Joining the aspatial long data to geospatial data:</h4>
<p>The aspatial data was joined to geospatial data using the column named “ADM1_EN” which consist of the province name of the Kingdom of Thailand.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>SAB1_tour_wide <span class="ot">&lt;-</span> <span class="fu">left_join</span>(SAB_1, tour_data_wide)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(SAB1_tour_wide,<span class="st">"data/rds/SAB1_tour_wide.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="reading-the-joined-aspatial-and-geospatial-data-from-rds-folder" class="level5">
<h5 class="anchored" data-anchor-id="reading-the-joined-aspatial-and-geospatial-data-from-rds-folder">Reading the joined aspatial and geospatial data from rds folder:</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>SAB1_tour_wide<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/SAB1_tour_wide.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="to-derive-foreign-tourists-related-spending-indicators-for-the-study-period." class="level3">
<h3 class="anchored" data-anchor-id="to-derive-foreign-tourists-related-spending-indicators-for-the-study-period.">To derive foreign tourists related spending indicators for the study period.</h3>
<p>As mentioned earlier, the focus of this analysis is on indicators related to the revenue generated from foreign tourism. Hence the main variables used for this analysis are:</p>
<ul>
<li><p>Total revenue generated from Foreign Tourists (Sum of Revenue_foreign ) from the Period of 2019 to 2023 by provinces.</p></li>
<li><p>Total number of foreign tourists (sum of no_tourist_foreign) from the Period of 2019 to 2023 by provinces.</p></li>
<li><p>Amount of Revenue generated by per Tourist (Amt_rev_per_for_tourist). This indicator is derived using the above using above two indicators, sum of Revenue_foreign divided by sum of no_tourist_foreign. This indicator will highlight the provinces are attracting foreign tourists with higher spending power.</p>
<p>The 3rd indicator is important for policy planning. In the context of the COVID-19, it is important for policy maker to be aware of the the province with higher spending foreign tourist. The Thai government can use this findings to isolate the area of Thailand to open up for foreign tourists and implement movement restriction measures if there is another pandemic were to occur. This will help policy measures to plan and develop plans to mitigate the impact of the pandemic on the economy and perform long term planning for a more pandemic resistance tourism industry in Thailand.</p></li>
</ul>
<p>The following code chunks is to derive the indicators as described above and join them to the province layer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>total_for_prov<span class="ot">&lt;-</span> tour_data_wide <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ADM1_EN) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_for_revenue =</span> <span class="fu">sum</span>(revenue_foreign), <span class="at">total_no_for_tourist=</span> <span class="fu">sum</span>(no_tourist_foreign))<span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Amt_rev_per_for_tourist=</span> (total_for_revenue <span class="sc">/</span>total_no_for_tourist))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(total_for_prov,<span class="st">"data/rds/total_for_prov.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>SAB_1_total_for_prov<span class="ot">&lt;-</span> <span class="fu">left_join</span>(SAB_1, total_for_prov)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(SAB_1_total_for_prov,<span class="st">"data/rds/SAB_1_total_for_prov.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To read the joined data from SAB_1 layer rds folder.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>SAB_1_total_for_prov<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/SAB_1_total_for_prov.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="preparation-thai_total_for_prov-layer-and-writing-it-to-rds-folder." class="level5">
<h5 class="anchored" data-anchor-id="preparation-thai_total_for_prov-layer-and-writing-it-to-rds-folder.">Preparation Thai_total_for_prov layer and writing it to rds folder.</h5>
<p>The following code is to trim layer to only the required columns for analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov <span class="ot">&lt;-</span> <span class="fu">subset</span>(SAB_1_total_for_prov , </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">select =</span> <span class="fu">c</span>(<span class="st">"Shape_Leng"</span>, <span class="st">"Shape_Area"</span>, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"ADM1_EN"</span>,<span class="st">"date"</span>, <span class="st">"total_for_revenue"</span>, </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"total_no_for_tourist"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Amt_rev_per_for_tourist"</span>, <span class="st">"geometry"</span>))</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(Thai_total_for_prov,<span class="st">"data/rds/Thai_total_for_prov.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/Thai_total_for_prov.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="visualising-foreign-tourists-indicators-for-year-2019-to-2023" class="level2">
<h2 class="anchored" data-anchor-id="visualising-foreign-tourists-indicators-for-year-2019-to-2023">Visualising Foreign Tourists Indicators for year 2019 to 2023</h2>
<p>The following code chunks are to generate visualise indicators using Tmap function by the equal interval and equal quantile method.</p>
<section id="total-revenue-from-foreign-tourists." class="level4">
<h4 class="anchored" data-anchor-id="total-revenue-from-foreign-tourists.">Total revenue from foreign tourists.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the map</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 12 #to widen the space</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 8 #to lengthen the graph.</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>equal_TotRev <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_for_revenue"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Total Revenue From </span><span class="sc">\n</span><span class="st"> Foreign Tourists"</span>) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Quantile Distribution of </span><span class="sc">\n</span><span class="st"> Total Revenue from Foreign Tourists by Provinces 2019 to 2023"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.6</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.4</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>quantile_TotRev<span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov) <span class="sc">+</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_for_revenue"</span>,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">style =</span> <span class="st">"equal"</span>,</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Total Revenue From </span><span class="sc">\n</span><span class="st"> Foreign Tourists"</span>) <span class="sc">+</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Interval Distribution of </span><span class="sc">\n</span><span class="st"> Total Revenue from Foreign Tourists by Provinces 2019 to 2023"</span>,</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.6</span>,</span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.4</span>,</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(equal_TotRev, </span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a>             quantile_TotRev, </span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, </span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the map</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 12 #to widen the space</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 8 #to lengthen the graph.</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>equal_nofor <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_no_for_tourist"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Total No. of Foreign Tourist"</span>) <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Quantile Distribution of Total No. of Foreign Tourist by </span><span class="sc">\n</span><span class="st"> Provinces 2019 to 2023"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.6</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.4</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>quantil_nofor<span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov) <span class="sc">+</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"total_no_for_tourist"</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">style =</span> <span class="st">"equal"</span>,</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Total no. of Foreign Tourist"</span>) <span class="sc">+</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Interval of Total No. of Foreign Tourist by </span><span class="sc">\n</span><span class="st"> Provinces 2019 to 2023"</span>,</span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.6</span>,</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.4</span>,</span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.4</span>,</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(equal_nofor, </span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>             quantil_nofor, </span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, </span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="amount-of-revenue-per-foreign-tourist" class="level3">
<h3 class="anchored" data-anchor-id="amount-of-revenue-per-foreign-tourist">Amount of Revenue per Foreign Tourist</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the map</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 12 #to widen the space</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 8 #to lengthen the graph.</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>equal_Amt <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"Amt_rev_per_for_tourist"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Amount of reveune per foreign Tourist"</span>) <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Quantile Distribution of </span><span class="sc">\n</span><span class="st"> Amount of reveune per Foreign Tourist by Provinces 2019 to 2023"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.6</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>quantil_Amt<span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov) <span class="sc">+</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"Amt_rev_per_for_tourist"</span>,</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">style =</span> <span class="st">"equal"</span>,</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>           <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Amount of reveune per foreign Tourist"</span>) <span class="sc">+</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Interval of Amount of reveune </span><span class="sc">\n</span><span class="st"> per Foreign Tourist by Provinces 2019 to 2023"</span>,</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.6</span>,</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>,</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(equal_Amt, </span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>             quantil_Amt, </span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, </span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="analyising-if-tourist-hotspot-is-related-to-space" class="level2">
<h2 class="anchored" data-anchor-id="analyising-if-tourist-hotspot-is-related-to-space">Analyising if Tourist hotspot is related to space</h2>
<p>We will start by analysing if the tourist hot-spots are related spatially.</p>
<p>Given that Phunket is an offshore island and has the one of the top 3 provinces in terms of total reveune from foreign tourists, hence contiguity matrix will not be suitable, we will need to use distance based matrix.</p>
<p>The following code chunk is to print the top 3 provinces with the highest revenue generated from the foreign tourists, highest number of foreign tourists and the highes amount of revune per foreign tourist for the period from 2019 to 2023.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>top_3_revenue <span class="ot">&lt;-</span> Thai_total_for_prov <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_for_revenue)) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>top_3_tourists <span class="ot">&lt;-</span> Thai_total_for_prov <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_no_for_tourist)) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>top_3_revenue_per_tourist <span class="ot">&lt;-</span> Thai_total_for_prov <span class="sc">%&gt;%</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Amt_rev_per_for_tourist)) <span class="sc">%&gt;%</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_3_revenue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 7 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 418207.3 ymin: 826705.1 xmax: 794817.5 ymax: 1543363
Projected CRS: WGS 84 / UTM zone 47N
  Shape_Leng Shape_Area   ADM1_EN       date total_for_revenue
1   2.417227 0.13133873   Bangkok 2019-02-18      1.106223e+12
2   2.920196 0.04494432    Phuket 2019-02-18      7.315906e+11
3   6.091786 0.37563008 Chon Buri 2019-02-18      2.999981e+11
  total_no_for_tourist Amt_rev_per_for_tourist                       geometry
1             44452634                24885.43 MULTIPOLYGON (((674339.8 15...
2             17525594                41744.13 MULTIPOLYGON (((424349 8267...
3             14660424                20463.13 MULTIPOLYGON (((714273.8 13...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_3_tourists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 7 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 418207.3 ymin: 826705.1 xmax: 794817.5 ymax: 1543363
Projected CRS: WGS 84 / UTM zone 47N
  Shape_Leng Shape_Area   ADM1_EN       date total_for_revenue
1   2.417227 0.13133873   Bangkok 2019-02-18      1.106223e+12
2   2.920196 0.04494432    Phuket 2019-02-18      7.315906e+11
3   6.091786 0.37563008 Chon Buri 2019-02-18      2.999981e+11
  total_no_for_tourist Amt_rev_per_for_tourist                       geometry
1             44452634                24885.43 MULTIPOLYGON (((674339.8 15...
2             17525594                41744.13 MULTIPOLYGON (((424349 8267...
3             14660424                20463.13 MULTIPOLYGON (((714273.8 13...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_3_revenue_per_tourist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 7 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 418207.3 ymin: 826705.1 xmax: 794817.5 ymax: 1543363
Projected CRS: WGS 84 / UTM zone 47N
  Shape_Leng Shape_Area   ADM1_EN       date total_for_revenue
1   2.920196 0.04494432    Phuket 2019-02-18      7.315906e+11
2   2.417227 0.13133873   Bangkok 2019-02-18      1.106223e+12
3   6.091786 0.37563008 Chon Buri 2019-02-18      2.999981e+11
  total_no_for_tourist Amt_rev_per_for_tourist                       geometry
1             17525594                41744.13 MULTIPOLYGON (((424349 8267...
2             44452634                24885.43 MULTIPOLYGON (((674339.8 15...
3             14660424                20463.13 MULTIPOLYGON (((714273.8 13...</code></pre>
</div>
</div>
</section>
<section id="exploratory-spatial-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-spatial-data-analysis">Exploratory Spatial Data Analysis:</h2>
<p>For this assignment, we will be focusing of using distance weight matrix. This is used due to there are many islands in Thailand being the tourist hot-spots.</p>
<section id="fixed-distance-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="fixed-distance-weight-matrix">Fixed Distance weight Matrix</h3>
<p>The following code chunk is to derive the spatial weight using distance based weight matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming Thai_total_for_pro has a geometry column in a projected CRS</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(Thai_total_for_prov, <span class="at">crs =</span> <span class="dv">4326</span>) <span class="co"># WGS84 CRS</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(Thai_total_for_prov<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(Thai_total_for_prov<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     longitude latitude
[1,]  100.6235 13.77183
[2,]  100.7102 13.59651
[3,]  100.3928 13.92416
[4,]  100.6824 14.06513
[5,]  100.5266 14.34535
[6,]  100.3485 14.62354</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>k1 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>k1dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">nbdists</span>(k1, coords, <span class="at">longlat =</span> <span class="cn">TRUE</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(k1dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21.55   51.92   64.33   63.24   76.77  110.94 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov<span class="sc">$</span>ADM1_EN[<span class="fu">match</span>(<span class="fu">max</span>(k1dists), k1dists)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Prachuap Khiri Khan"</code></pre>
</div>
</div>
<p>Since the maximum distance for the distance from one province to another is at 110.94, we will use 111 to build the fixed distance matrix.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Based on the max distance from the fix distance neighbour </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>wm_d111 <span class="ot">&lt;-</span> <span class="fu">dnearneigh</span>(coords, <span class="dv">0</span>, <span class="dv">111</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>) </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>wm_d111</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 350 
Percentage nonzero weights: 5.903188 
Average number of links: 4.545455 
2 disjoint connected subgraphs</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wm_d111)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 77
 $ : int [1:12] 2 3 4 5 6 10 11 15 17 59 ...
 $ : int [1:10] 1 3 4 5 11 15 17 59 60 61
 $ : int [1:13] 1 2 4 5 6 8 10 17 56 58 ...
 $ : int [1:14] 1 2 3 5 6 8 10 15 16 17 ...
 $ : int [1:13] 1 2 3 4 6 7 8 9 10 17 ...
 $ : int [1:11] 1 3 4 5 7 8 9 10 17 58 ...
 $ : int [1:7] 5 6 8 9 10 17 48
 $ : int [1:10] 3 4 5 6 7 9 10 48 49 58
 $ : int [1:7] 5 6 7 8 48 49 58
 $ : int [1:9] 1 3 4 5 6 7 8 16 17
 $ : int [1:6] 1 2 12 13 15 16
 $ : int [1:3] 11 13 15
 $ : int [1:5] 11 12 14 15 18
 $ : int 13
 $ : int [1:9] 1 2 4 11 12 13 16 17 18
 $ : int [1:6] 4 10 11 15 17 18
 $ : int [1:10] 1 2 3 4 5 6 7 10 15 16
 $ : int [1:3] 13 15 16
 $ : int 20
 $ : int [1:2] 19 21
 $ : int [1:2] 20 22
 $ : int [1:2] 21 23
 $ : int [1:2] 22 26
 $ : int [1:3] 26 34 38
 $ : int [1:2] 29 55
 $ : int [1:4] 23 24 34 38
 $ : int [1:2] 32 36
 $ : int [1:4] 29 30 31 32
 $ : int [1:3] 25 28 33
 $ : int [1:3] 28 32 36
 $ : int 28
 $ : int [1:3] 27 28 30
 $ : int [1:3] 29 34 35
 $ : int [1:5] 24 26 33 35 38
 $ : int [1:4] 33 34 36 38
 $ : int [1:4] 27 30 35 37
 $ : int [1:2] 36 38
 $ : int [1:5] 24 26 34 35 37
 $ : int [1:3] 40 41 47
 $ : int [1:2] 39 41
 $ : int [1:3] 39 40 43
 $ : int [1:3] 43 52 53
 $ : int [1:4] 41 42 44 52
 $ : int [1:2] 43 45
 $ : int [1:2] 44 46
 $ : int 45
 $ : int 39
 $ : int [1:6] 7 8 9 49 50 54
 $ : int [1:6] 8 9 48 50 57 58
 $ : int [1:5] 48 49 51 52 54
 $ : int 50
 $ : int [1:4] 42 43 50 53
 $ : int [1:4] 42 52 54 55
 $ : int [1:4] 48 50 53 55
 $ : int [1:3] 25 53 54
 $ : int [1:5] 3 59 60 61 62
 $ : int [1:2] 49 58
 $ : int [1:9] 3 4 5 6 8 9 49 57 59
 $ : int [1:10] 1 2 3 4 5 6 56 58 60 61
 $ : int [1:9] 1 2 3 4 5 56 59 61 62
 $ : int [1:8] 1 2 3 4 56 59 60 62
 $ : int [1:4] 56 60 61 63
 $ : int 62
 $ : int [1:4] 65 68 73 74
 $ : int [1:5] 64 66 67 68 73
 $ : int [1:3] 65 67 68
 $ : int [1:2] 65 66
 $ : int [1:4] 64 65 66 69
 $ : int [1:2] 68 70
 $ : int 69
 $ : int [1:3] 72 74 75
 $ : int [1:3] 71 73 74
 $ : int [1:4] 64 65 72 74
 $ : int [1:4] 64 71 72 73
 $ : int [1:3] 71 76 77
 $ : int [1:2] 75 77
 $ : int [1:2] 75 76
 - attr(*, "class")= chr "nb"
 - attr(*, "region.id")= chr [1:77] "1" "2" "3" "4" ...
 - attr(*, "call")= language dnearneigh(x = coords, d1 = 0, d2 = 111, longlat = TRUE)
 - attr(*, "dnn")= num [1:2] 0 111
 - attr(*, "bounds")= chr [1:2] "GE" "LE"
 - attr(*, "nbtype")= chr "distance"
 - attr(*, "sym")= logi TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN, <span class="fu">card</span>(wm_d111))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          
                           1 2 3 4 5 6 7 8 9 10 11 12 13 14
  Amnat Charoen            0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Ang Thong                0 0 0 0 0 0 0 0 0  0  1  0  0  0
  Bangkok                  0 0 0 0 0 0 0 0 0  0  0  1  0  0
  Bueng Kan                0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Buri Ram                 0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Chachoengsao             0 0 0 0 0 0 0 0 1  0  0  0  0  0
  Chai Nat                 0 0 0 0 0 0 1 0 0  0  0  0  0  0
  Chaiyaphum               0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Chanthaburi              0 0 0 0 1 0 0 0 0  0  0  0  0  0
  Chiang Mai               0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Chiang Rai               1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Chon Buri                0 0 0 0 0 1 0 0 0  0  0  0  0  0
  Chumphon                 1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Kalasin                  0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Kamphaeng Phet           0 0 0 0 1 0 0 0 0  0  0  0  0  0
  Kanchanaburi             0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Khon Kaen                0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Krabi                    0 0 0 0 1 0 0 0 0  0  0  0  0  0
  Lampang                  0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Lamphun                  0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Loei                     1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Lop Buri                 0 0 0 0 0 0 1 0 0  0  0  0  0  0
  Mae Hong Son             1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Maha Sarakham            0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Mukdahan                 0 0 0 0 1 0 0 0 0  0  0  0  0  0
  Nakhon Nayok             0 0 0 0 0 0 0 0 0  1  0  0  0  0
  Nakhon Pathom            0 0 0 0 0 0 0 0 0  1  0  0  0  0
  Nakhon Phanom            0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Nakhon Ratchasima        1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Nakhon Sawan             0 0 0 0 0 1 0 0 0  0  0  0  0  0
  Nakhon Si Thammarat      0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Nan                      0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Narathiwat               0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Nong Bua Lam Phu         0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Nong Khai                0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Nonthaburi               0 0 0 0 0 0 0 0 0  0  0  0  1  0
  Pathum Thani             0 0 0 0 0 0 0 0 0  0  0  0  0  1
  Pattani                  0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Phangnga                 0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Phatthalung              0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Phayao                   0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Phetchabun               0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Phetchaburi              0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Phichit                  0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Phitsanulok              0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Phra Nakhon Si Ayutthaya 0 0 0 0 0 0 0 0 0  0  0  0  1  0
  Phrae                    0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Phuket                   0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Prachin Buri             0 0 0 0 0 1 0 0 0  0  0  0  0  0
  Prachuap Khiri Khan      1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Ranong                   0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Ratchaburi               0 0 0 0 1 0 0 0 0  0  0  0  0  0
  Rayong                   0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Roi Et                   0 0 0 0 1 0 0 0 0  0  0  0  0  0
  Sa Kaeo                  0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Sakon Nakhon             0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Samut Prakan             0 0 0 0 0 0 0 0 0  1  0  0  0  0
  Samut Sakhon             0 0 0 0 0 0 0 0 1  0  0  0  0  0
  Samut Songkhram          0 0 0 0 0 0 0 1 0  0  0  0  0  0
  Saraburi                 0 0 0 0 0 0 0 0 1  0  0  0  0  0
  Satun                    0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Si Sa Ket                0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Sing Buri                0 0 0 0 0 0 0 0 0  1  0  0  0  0
  Songkhla                 0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Sukhothai                0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Suphan Buri              0 0 0 0 0 0 0 0 1  0  0  0  0  0
  Surat Thani              0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Surin                    0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Tak                      1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Trang                    0 0 0 1 0 0 0 0 0  0  0  0  0  0
  Trat                     1 0 0 0 0 0 0 0 0  0  0  0  0  0
  Ubon Ratchathani         0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Udon Thani               0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Uthai Thani              0 0 0 0 0 1 0 0 0  0  0  0  0  0
  Uttaradit                0 0 1 0 0 0 0 0 0  0  0  0  0  0
  Yala                     0 1 0 0 0 0 0 0 0  0  0  0  0  0
  Yasothon                 0 0 1 0 0 0 0 0 0  0  0  0  0  0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>n_comp <span class="ot">&lt;-</span> <span class="fu">n.comp.nb</span>(wm_d111)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>n_comp<span class="sc">$</span>nc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(n_comp<span class="sc">$</span>comp.id)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 1  2 
63 14 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Thai_total_for_prov<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"1st nearest neighbours"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k1, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">length=</span><span class="fl">0.08</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Thai_total_for_prov<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Distance link"</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d111, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations-from-the-fixed-distance-matrix." class="level4">
<h4 class="anchored" data-anchor-id="observations-from-the-fixed-distance-matrix.">Observations from the fixed distance matrix.</h4>
<p>Based on the outputs generated by fixed distance matrix, it is observed that the fixed distance matrix will generate a number of 7 provinces with only 1 neighbour, this is not ideal. Hence adaptive distance matrix is built.</p>
</section>
</section>
<section id="adaptive-distanace-weight-matrix" class="level3">
<h3 class="anchored" data-anchor-id="adaptive-distanace-weight-matrix">Adaptive Distanace weight matrix</h3>
<p>The following codes are to build the adaptive distance weight matrix, Examining if Adaptive distance weight matrix will be more suitable for the Analysis. Hence similar to the hands on exercise, we will use 6 nearest neighbours.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>knn6 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k=</span><span class="dv">6</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 77 
Number of nonzero links: 462 
Percentage nonzero weights: 7.792208 
Average number of links: 6 
Non-symmetric neighbours list</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 77
 $ : int [1:6] 2 3 4 5 59 60
 $ : int [1:6] 1 3 4 11 59 60
 $ : int [1:6] 1 2 4 5 59 60
 $ : int [1:6] 1 2 3 5 17 59
 $ : int [1:6] 1 3 4 6 8 10
 $ : int [1:6] 4 5 8 9 10 58
 $ : int [1:6] 5 6 8 9 10 17
 $ : int [1:6] 5 6 7 9 10 58
 $ : int [1:6] 6 7 8 48 49 58
 $ : int [1:6] 4 5 6 7 8 17
 $ : int [1:6] 1 2 12 13 15 16
 $ : int [1:6] 2 11 13 14 15 16
 $ : int [1:6] 11 12 14 15 16 18
 $ : int [1:6] 11 12 13 15 16 18
 $ : int [1:6] 1 2 11 12 16 17
 $ : int [1:6] 4 10 11 15 17 18
 $ : int [1:6] 1 4 5 10 15 16
 $ : int [1:6] 13 15 16 17 19 20
 $ : int [1:6] 10 16 17 18 20 25
 $ : int [1:6] 18 19 21 22 33 34
 $ : int [1:6] 20 22 24 26 33 34
 $ : int [1:6] 20 21 23 24 26 34
 $ : int [1:6] 21 22 24 26 34 38
 $ : int [1:6] 22 23 26 34 35 38
 $ : int [1:6] 7 19 28 29 33 55
 $ : int [1:6] 22 23 24 34 35 38
 $ : int [1:6] 28 30 32 35 36 37
 $ : int [1:6] 25 29 30 31 32 35
 $ : int [1:6] 25 28 30 33 34 35
 $ : int [1:6] 27 28 29 32 35 36
 $ : int [1:6] 28 30 32 42 53 55
 $ : int [1:6] 27 28 30 31 35 36
 $ : int [1:6] 20 21 24 29 34 35
 $ : int [1:6] 21 24 26 33 35 38
 $ : int [1:6] 24 29 33 34 36 38
 $ : int [1:6] 27 30 32 35 37 38
 $ : int [1:6] 24 26 27 35 36 38
 $ : int [1:6] 24 26 34 35 36 37
 $ : int [1:6] 40 41 43 45 46 47
 $ : int [1:6] 39 41 43 47 51 52
 $ : int [1:6] 39 40 42 43 45 52
 $ : int [1:6] 31 41 43 44 52 53
 $ : int [1:6] 40 41 42 44 45 52
 $ : int [1:6] 31 41 42 43 45 46
 $ : int [1:6] 39 41 42 43 44 46
 $ : int [1:6] 39 40 41 43 44 45
 $ : int [1:6] 39 40 41 43 45 46
 $ : int [1:6] 7 8 9 49 50 54
 $ : int [1:6] 8 9 48 50 57 58
 $ : int [1:6] 48 49 51 52 53 54
 $ : int [1:6] 40 48 49 50 52 54
 $ : int [1:6] 41 42 43 50 51 53
 $ : int [1:6] 31 42 50 52 54 55
 $ : int [1:6] 9 48 50 52 53 55
 $ : int [1:6] 7 25 31 48 53 54
 $ : int [1:6] 1 3 59 60 61 62
 $ : int [1:6] 6 9 49 56 58 59
 $ : int [1:6] 5 6 8 9 49 59
 $ : int [1:6] 1 3 4 5 60 61
 $ : int [1:6] 1 2 3 56 59 61
 $ : int [1:6] 1 3 56 59 60 62
 $ : int [1:6] 3 56 59 60 61 63
 $ : int [1:6] 2 56 60 61 62 70
 $ : int [1:6] 65 66 67 68 73 74
 $ : int [1:6] 64 66 67 68 73 74
 $ : int [1:6] 64 65 67 68 69 73
 $ : int [1:6] 64 65 66 68 73 74
 $ : int [1:6] 64 65 66 67 69 70
 $ : int [1:6] 64 65 66 67 68 70
 $ : int [1:6] 63 64 65 66 68 69
 $ : int [1:6] 72 73 74 75 76 77
 $ : int [1:6] 64 71 73 74 75 76
 $ : int [1:6] 64 65 67 71 72 74
 $ : int [1:6] 64 65 71 72 73 75
 $ : int [1:6] 71 72 73 74 76 77
 $ : int [1:6] 71 72 73 74 75 77
 $ : int [1:6] 71 72 73 74 75 76
 - attr(*, "region.id")= chr [1:77] "1" "2" "3" "4" ...
 - attr(*, "call")= language knearneigh(x = coords, k = 6)
 - attr(*, "sym")= logi FALSE
 - attr(*, "type")= chr "knn"
 - attr(*, "knn-k")= num 6
 - attr(*, "class")= chr "nb"</code></pre>
</div>
</div>
</section>
<section id="plotting-adaptive-distance-based-neighbours" class="level3">
<h3 class="anchored" data-anchor-id="plotting-adaptive-distance-based-neighbours">Plotting Adaptive Distance-based Neighbours</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Thai_total_for_prov<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>,<span class="at">main=</span><span class="st">"6 nearest neighbours"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(knn6, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(Thai_total_for_prov<span class="sc">$</span>geometry, <span class="at">border=</span><span class="st">"lightgrey"</span>, <span class="at">main=</span><span class="st">"Distance link"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wm_d111, coords, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations-from-the-fixed-distance-matrix.-1" class="level4">
<h4 class="anchored" data-anchor-id="observations-from-the-fixed-distance-matrix.-1">Observations from the fixed distance matrix.</h4>
<p>It is noted that the adaptive distance matrix maybe more suitable for this analysis due to standardization of neighbours, given there are many islands in Thailand and geographical layout of Thailand.</p>
<p>As part of the exploration, the row standardized weights matrix, were built using the both adaptive and fixed distance martix.</p>
</section>
</section>
<section id="row-standardised-weights-martix" class="level3">
<h3 class="anchored" data-anchor-id="row-standardised-weights-martix">Row-Standardised Weights martix</h3>
<section id="using-fixed-distance-martix" class="level4">
<h4 class="anchored" data-anchor-id="using-fixed-distance-martix">Using fixed distance martix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>rswm_d111 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wm_d111, <span class="at">style=</span><span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>rswm_d111</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 77 
Number of nonzero links: 350 
Percentage nonzero weights: 5.903188 
Average number of links: 4.545455 
2 disjoint connected subgraphs

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 77 5929 77 49.37234 320.9424</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>rswm_d111<span class="sc">$</span>weights[<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.1111111 0.1111111 0.1111111 0.1111111 0.1111111 0.1111111 0.1111111
[8] 0.1111111 0.1111111</code></pre>
</div>
</div>
</section>
<section id="using-adaoptive-distance-martix" class="level4">
<h4 class="anchored" data-anchor-id="using-adaoptive-distance-martix">Using adaoptive distance martix</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>rswm_knn6 <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn6, <span class="at">style=</span><span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>rswm_knn6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 77 
Number of nonzero links: 462 
Percentage nonzero weights: 7.792208 
Average number of links: 6 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
   n   nn S0       S1       S2
W 77 5929 77 22.77778 319.4444</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>rswm_knn6<span class="sc">$</span>weights[<span class="dv">10</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="spatial-lag-with-row-standardized-weights" class="level2">
<h2 class="anchored" data-anchor-id="spatial-lag-with-row-standardized-weights">Spatial lag with row-standardized weights</h2>
<p>Finally, we’ll compute the average neighbor values for the 3 foreign tourist indicators for each polygon. These values are often referred to as spatially lagged values. As discussed in the earlier session, we will be creating using the adaptive distance matrix, hence rswm_knn6 will be used.</p>
<p>This section, we will be deriving the row standadised weight matrix for each indicators.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>Total_rev.lag <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_knn6, Thai_total_for_prov<span class="sc">$</span>total_for_revenue)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>Total_rev.lag</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   2632245700 234844619033 186852994917 186759552700 184834014117
 [6]   1656020000   1405093667   1411425333     68396667   1634931333
[11] 186485341667  52891616667  53162270000  51428566667 236382986667
[16]  50479650000 186110098333    542488333    371410333    435401667
[21]    104560000    246893333    166201667    269321667    400613333
[26]    271233333    709568333    780531667    316098333    468840000
[31]    891513333    347095000    205848333    162133333    225955000
[36]    813895000    142653333     87833333   2909921667  12347825000
[41]  11684091667    753618333    548273333   2378015000  13625095000
[46]  11561738333  13642661667     40811667    588846667    573758333
[51]    379753333    457740000    409405000    586491667    272226667
[56] 185588416033    142260250   1404896917 186144302117 185488927700
[61] 185608924367   3300536033   2028108333 165495163333 150208280000
[66] 155790093333  43641733333 147462251667 165331390000  46352168333
[71]   1736048333   9136983333 145637320000  24073928333   9763171667
[76]   9126200000   9280406667</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> knn6[[<span class="dv">1</span>]]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>nb1 <span class="ot">&lt;-</span> Thai_total_for_prov<span class="sc">$</span>total_for_revenue[nb1]</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>nb1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4971250000  898464700 1569688000 7975590000  358861500   19620000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>lag.list <span class="ot">&lt;-</span> <span class="fu">list</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN, <span class="fu">lag.listw</span>(rswm_knn6, Thai_total_for_prov<span class="sc">$</span>total_for_revenue))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list)</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADM1_EN"</span>, <span class="st">"lag.total_for_revenue"</span>)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov<span class="ot">&lt;-</span> <span class="fu">left_join</span>(Thai_total_for_prov,lag.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>lag.list <span class="ot">&lt;-</span> <span class="fu">list</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN, <span class="fu">lag.listw</span>(rswm_knn6,Thai_total_for_prov<span class="sc">$</span>total_no_for_tourist))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADM1_EN"</span>, <span class="st">"lag.total_no_for_tourist"</span>)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov<span class="ot">&lt;-</span> <span class="fu">left_join</span>(Thai_total_for_prov,lag.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>lag.list <span class="ot">&lt;-</span> <span class="fu">list</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN, <span class="fu">lag.listw</span>(rswm_knn6,Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>lag.res <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(lag.list)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(lag.res) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADM1_EN"</span>, <span class="st">"lag.Amt_rev_per_for_tourist"</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov<span class="ot">&lt;-</span> <span class="fu">left_join</span>(Thai_total_for_prov,lag.res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Thai_total_for_prov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 100.1913 ymin: 13.47842 xmax: 100.9639 ymax: 14.80246
Geodetic CRS:  WGS 84
  Shape_Leng Shape_Area                  ADM1_EN       date total_for_revenue
1   2.417227 0.13133873                  Bangkok 2019-02-18      1.106223e+12
2   1.695100 0.07926199             Samut Prakan 2019-02-18      4.971250e+09
3   1.251111 0.05323766               Nonthaburi 2019-02-18      8.984647e+08
4   1.884945 0.12698345             Pathum Thani 2019-02-18      1.569688e+09
5   3.041716 0.21393797 Phra Nakhon Si Ayutthaya 2019-02-18      7.975590e+09
6   1.739908 0.07920961                Ang Thong 2019-02-18      4.717000e+07
  total_no_for_tourist Amt_rev_per_for_tourist lag.total_for_revenue
1             44452634               24885.431            2632245700
2              2183088                2277.164          234844619033
3               403338                2227.573          186852994917
4               750370                2091.885          186759552700
5              2961839                2692.783          184834014117
6                42073                1121.147            1656020000
  lag.total_no_for_tourist lag.Amt_rev_per_for_tourist
1                1080228.0                    2205.005
2               10074916.5                    8934.774
3                8421777.3                    5981.315
4                8368454.0                    6270.697
5                7631444.5                    5676.711
6                 653539.7                    1976.673
                        geometry
1 MULTIPOLYGON (((100.6139 13...
2 MULTIPOLYGON (((100.7306 13...
3 MULTIPOLYGON (((100.3415 14...
4 MULTIPOLYGON (((100.8916 14...
5 MULTIPOLYGON (((100.5131 14...
6 MULTIPOLYGON (((100.3332 14...</code></pre>
</div>
</div>
<p>After deriving the spatial lag indicators, the following code chunks is to plot them to view the differences between them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>Total_no <span class="ot">&lt;-</span> <span class="fu">qtm</span>(Thai_total_for_prov, <span class="st">"total_no_for_tourist"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>lag_no <span class="ot">&lt;-</span> <span class="fu">qtm</span>(Thai_total_for_prov, <span class="st">"lag.total_no_for_tourist"</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Total_no , lag_no, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>amt <span class="ot">&lt;-</span> <span class="fu">qtm</span>(Thai_total_for_prov, <span class="st">"Amt_rev_per_for_tourist"</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>lag_amt <span class="ot">&lt;-</span> <span class="fu">qtm</span>(Thai_total_for_prov, <span class="st">"lag.Amt_rev_per_for_tourist"</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(amt, lag_amt, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>Total_rev <span class="ot">&lt;-</span> <span class="fu">qtm</span>(Thai_total_for_prov, <span class="st">"total_for_revenue"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>lag_Total_rev <span class="ot">&lt;-</span> <span class="fu">qtm</span>(Thai_total_for_prov, <span class="st">"lag.total_for_revenue"</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Total_rev, lag_Total_rev, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>##Computing Global Spatial Autocorrelation Statistics</p>
<p>Next we will be carrying out test to find if there is any spatial correlation in the tourist hot-spots.</p>
<ul>
<li><p>H0: Observed spatial patterns of values is equally, data is randomly disbursed and no spatial pattern</p></li>
<li><p>H1: Data is more spatially clustered.</p></li>
</ul>
<section id="computing-global-moran-i" class="level3">
<h3 class="anchored" data-anchor-id="computing-global-moran-i">Computing Global Moran’ I</h3>
<p>Moran’s I statistical test was performed by using moran.test() of spdep. Moran’s I describe how features differ from the values in the study area as a whole. The Moran I statistic ranges from -1 to 1. If the Moran I is:</p>
<ul>
<li><p>positive (I &gt;0): Clustered, observations tend to be similar</p></li>
<li><p>negative (I &lt;0): Disperse, observations tend to be dissimilar</p></li>
<li><p>approximately or near to zero: observations arranged randomly over space</p></li>
</ul>
<section id="total-revenue-from-foreign-tourist." class="level4">
<h4 class="anchored" data-anchor-id="total-revenue-from-foreign-tourist.">Total Revenue from Foreign Tourist.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(Thai_total_for_prov<span class="sc">$</span>total_for_revenue, </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rswm_knn6, </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  Thai_total_for_prov$total_for_revenue  
weights: rswm_knn6    

Moran I statistic standard deviate = 0.50503, p-value = 0.3068
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.008385629      -0.013157895       0.001819717 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>bperm_tot <span class="ot">=</span> <span class="fu">moran.mc</span>(Thai_total_for_prov<span class="sc">$</span>total_for_revenue, </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">listw =</span> rswm_knn6,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">zero.policy =</span> <span class="cn">TRUE</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.action =</span> na.omit)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>bperm_tot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  Thai_total_for_prov$total_for_revenue 
weights: rswm_knn6  
number of simulations + 1: 100 

statistic = 0.0083856, observed rank = 83, p-value = 0.17
alternative hypothesis: greater</code></pre>
</div>
</div>
</section>
<section id="observation-on-the-global-moran-test-for-total-revenue-generated-from-foreign-tourists" class="level4">
<h4 class="anchored" data-anchor-id="observation-on-the-global-moran-test-for-total-revenue-generated-from-foreign-tourists">Observation on the global Moran test for total revenue generated from foreign tourists</h4>
<p>The statistical report on shows that the p-value is larger than alpha value of 0.05. Hence, we don’t have statistical evidence to reject the null hypothesis that the spatial distribution of total foreign spending in Thailand may resemble random distribution (i.e.&nbsp;independent from spatial). Because the Moran’s I statistics is close 0. We can infer that the spatial distribution shows sign of randomness and is not related to spatial.</p>
</section>
<section id="total-number-of-foreign-tourist" class="level4">
<h4 class="anchored" data-anchor-id="total-number-of-foreign-tourist">Total number of foreign tourist</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(Thai_total_for_prov<span class="sc">$</span>total_no_for_tourist, </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rswm_knn6, </span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  Thai_total_for_prov$total_no_for_tourist  
weights: rswm_knn6    

Moran I statistic standard deviate = 1.3917, p-value = 0.08201
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.040939058      -0.013157895       0.001511068 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>bperm_noFor <span class="ot">=</span> <span class="fu">moran.mc</span>(Thai_total_for_prov<span class="sc">$</span>total_no_for_tourist, </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">listw =</span> rswm_knn6,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">zero.policy =</span> <span class="cn">TRUE</span>,</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.action =</span> na.omit)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>bperm_noFor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  Thai_total_for_prov$total_no_for_tourist 
weights: rswm_knn6  
number of simulations + 1: 100 

statistic = 0.040939, observed rank = 91, p-value = 0.09
alternative hypothesis: greater</code></pre>
</div>
</div>
</section>
<section id="observation-on-the-global-moran-test-for-total-number-of-foreign-tourist." class="level4">
<h4 class="anchored" data-anchor-id="observation-on-the-global-moran-test-for-total-number-of-foreign-tourist.">Observation on the global Moran test for total number of foreign tourist.</h4>
<p>The statistical report on shows that the p-value is larger than alpha value of 0.05. Hence, we don’t have statistical evidence to reject the null hypothesis that the spatial distribution of total number of foreign tourists in Thailand may resemble random distribution (i.e.&nbsp;independent from spatial). Because the Moran’s I statistics is close 0. We can infer that the spatial distribution shows sign of randomness and is not related to spatial</p>
</section>
<section id="amount-of-spending-per-foreign-tourist" class="level4">
<h4 class="anchored" data-anchor-id="amount-of-spending-per-foreign-tourist">Amount of spending per foreign tourist</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist, </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">listw=</span>rswm_knn6, </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, </span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">na.action=</span>na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  Thai_total_for_prov$Amt_rev_per_for_tourist  
weights: rswm_knn6    

Moran I statistic standard deviate = 4.9032, p-value = 4.713e-07
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
       0.24538650       -0.01315789        0.00278038 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>bperm_Amt <span class="ot">=</span> <span class="fu">moran.mc</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist, </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">listw =</span> rswm_knn6,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">nsim =</span> <span class="dv">99</span>,</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">zero.policy =</span> <span class="cn">TRUE</span>,</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">na.action =</span> na.omit)</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>bperm_Amt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  Thai_total_for_prov$Amt_rev_per_for_tourist 
weights: rswm_knn6  
number of simulations + 1: 100 

statistic = 0.24539, observed rank = 99, p-value = 0.01
alternative hypothesis: greater</code></pre>
</div>
</div>
</section>
<section id="observation-on-the-global-moran-test-for-the-amount-of-spending-per-foreign-tourist" class="level4">
<h4 class="anchored" data-anchor-id="observation-on-the-global-moran-test-for-the-amount-of-spending-per-foreign-tourist">Observation on the global Moran test for the amount of spending per foreign tourist</h4>
<p>Given the p-value is less than alpha at 0.05, we have statistical evidence to reject the null hypothesis. The Moran’s I statistic of 0.248 suggests a moderate positive spatial autocorrelation. This means that provinces in Thailand with higher revenue per tourist tend have be close together. However given the statistic is less than 0.5, this show that the spatial autocorrelation is not strong.</p>
</section>
<section id="histogram-for-on-global-moran-simulation-for-the-amount-of-revenue-generated-by-foreign-tourist." class="level4">
<h4 class="anchored" data-anchor-id="histogram-for-on-global-moran-simulation-for-the-amount-of-revenue-generated-by-foreign-tourist.">Histogram for on Global Moran Simulation for the amount of revenue generated by foreign tourist.</h4>
<p>Given that only amount generated per foreign tourist has statistically significant results from the statistical test from global Moran I test, only the Monte-Carlo simulation will be plotted in histogram.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(bperm_Amt<span class="sc">$</span>res)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Simulated Moran's I"</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>moran_amt <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">Simulated Moran's I</span><span class="st">`</span>)) <span class="sc">+</span> </span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"grey"</span>, <span class="at">bins =</span> <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="sc">-</span><span class="fl">0.1</span>,<span class="fl">0.6</span>) <span class="sc">+</span> </span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Frequency'</span>) <span class="sc">+</span> </span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span>  <span class="fl">0.24538650</span>  , <span class="at">color =</span> <span class="st">'blue'</span>) <span class="sc">+</span> </span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Histogram of Monte Carlo Simulated </span><span class="sc">\n</span><span class="st">Moran's I (Amount Spent per foreign tourist)"</span>) <span class="sc">+</span></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.35</span>, <span class="at">y =</span> <span class="dv">50</span>, <span class="at">label =</span> <span class="st">"Actual Moran's I"</span>, <span class="at">color =</span> <span class="st">'blue'</span>) </span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>moran_amt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="gearys-c-test" class="level3">
<h3 class="anchored" data-anchor-id="gearys-c-test">Geary’s C Test</h3>
<ul>
<li><p>Large (c&gt;1): Dispersed, observations tend to be dissimilar</p></li>
<li><p>Small (c&lt;1): Clustered, observations tend to be similar</p></li>
<li><p>c near 1 1: observations are randomly over space</p></li>
</ul>
<section id="total-revenue-from-foreign-tourist.-1" class="level4">
<h4 class="anchored" data-anchor-id="total-revenue-from-foreign-tourist.-1">Total Revenue from Foreign Tourist.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geary.test</span>(Thai_total_for_prov<span class="sc">$</span>total_for_revenue, <span class="at">listw =</span> rswm_knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Geary C test under randomisation

data:  Thai_total_for_prov$total_for_revenue 
weights: rswm_knn6   

Geary C statistic standard deviate = -1.7145, p-value = 0.9568
alternative hypothesis: Expectation greater than statistic
sample estimates:
Geary C statistic       Expectation          Variance 
       1.24304833        1.00000000        0.02009688 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geary.test</span>(Thai_total_for_prov<span class="sc">$</span>total_no_for_tourist, <span class="at">listw =</span> rswm_knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Geary C test under randomisation

data:  Thai_total_for_prov$total_no_for_tourist 
weights: rswm_knn6   

Geary C statistic standard deviate = -1.6758, p-value = 0.9531
alternative hypothesis: Expectation greater than statistic
sample estimates:
Geary C statistic       Expectation          Variance 
       1.25431950        1.00000000        0.02303206 </code></pre>
</div>
</div>
</section>
<section id="amount-of-spending-per-foreign-tourist-1" class="level4">
<h4 class="anchored" data-anchor-id="amount-of-spending-per-foreign-tourist-1">Amount of spending per foreign tourist</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geary.test</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist, <span class="at">listw =</span> rswm_knn6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Geary C test under randomisation

data:  Thai_total_for_prov$Amt_rev_per_for_tourist 
weights: rswm_knn6   

Geary C statistic standard deviate = 1.9447, p-value = 0.0259
alternative hypothesis: Expectation greater than statistic
sample estimates:
Geary C statistic       Expectation          Variance 
       0.79639732        1.00000000        0.01096118 </code></pre>
</div>
</div>
<p><strong>Computing Monte Carlo Geary’s C</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>bperm_G_Amt <span class="ot">=</span> <span class="fu">geary.mc</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist,</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">listw =</span> rswm_knn6,</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">nsim =</span> <span class="dv">99</span>)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>bperm_G_Amt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Geary C

data:  Thai_total_for_prov$Amt_rev_per_for_tourist 
weights: rswm_knn6  
number of simulations + 1: 100 

statistic = 0.7964, observed rank = 1, p-value = 0.01
alternative hypothesis: greater</code></pre>
</div>
</div>
</section>
<section id="observation-from-gearys-c-for-amount-spent-per-foreign-tourists" class="level4">
<h4 class="anchored" data-anchor-id="observation-from-gearys-c-for-amount-spent-per-foreign-tourists">Observation from <strong>Geary’s C for Amount Spent per Foreign Tourists</strong></h4>
<p>Given the p-value is less than alpha at 0.05, we have statistical evidence to reject the null hypothesis. The Geary’‘s C’ statistic of 0.248 suggests a moderate spatial autocorrelation. This means that provinces in Thailand with higher revenue per tourist tend have be close together. However given the statistic is less than 0.5, this show that the spatial autocorrelation is not strong.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>moran_corr_Amt<span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(knn6, <span class="co">#non-weighted spatial weights</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>                          Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist,</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">order =</span> <span class="dv">6</span>,</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">'I'</span>, <span class="co">#Moran's I</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">style =</span> <span class="st">'W'</span>) <span class="co">#weighed</span></span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(moran_corr_Amt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(moran_corr_Amt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial correlogram for Thai_total_for_prov$Amt_rev_per_for_tourist 
method: Moran's I
         estimate expectation   variance standard deviate Pr(I) two sided    
1 (77)  0.2453865  -0.0131579  0.0027804           4.9032       9.427e-07 ***
2 (77)  0.0738698  -0.0131579  0.0020621           1.9165         0.05531 .  
3 (77)  0.0477061  -0.0131579  0.0019047           1.3946         0.16314    
4 (77) -0.0017183  -0.0131579  0.0017711           0.2718         0.78576    
5 (77)  0.0487384  -0.0131579  0.0016770           1.5115         0.13067    
6 (77) -0.0481046  -0.0131579  0.0015967          -0.8746         0.38180    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From the output, we can see that the amount of revenue per tourists is not spatially correlated. you can see that there is no standard trend as the spatial lags increases beyond 6. Due to the time limit of the assignment, I am unable to try if the results will improve if I were to change the adaptative matrix from 6 to 4.</p>
</section>
</section>
<section id="computing-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="computing-local-morans-i">Computing local Moran’s I</h3>
<p>Next we will compute the local Moran’s I, using the localmoran() function of spdep package.Due to the time constraints, the indicators to focus on will be the Amount of revenue per foreign tourist, given that the Global Moran test has shown significant results, however it is important to note that it is still possible that there are local spatial correlations for the other two indicators.</p>
<section id="amount-of-revenue-per-foreign-tourits" class="level4">
<h4 class="anchored" data-anchor-id="amount-of-revenue-per-foreign-tourits">Amount of revenue per foreign tourits</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>fips_amt <span class="ot">&lt;-</span> <span class="fu">order</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>localMI_amt <span class="ot">&lt;-</span> <span class="fu">localmoran</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist, rswm_knn6)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(localMI_amt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Ii         E.Ii     Var.Ii       Z.Ii Pr(z != E(Ii))
1 -1.50804432 -0.129839209 1.35326117 -1.1847400      0.2361203
2 -0.27853733 -0.002888650 0.03449966 -1.4840499      0.1377957
3 -0.05855375 -0.002987109 0.03567205 -0.2942051      0.7686012
4 -0.08423260 -0.003264935 0.03897899 -0.4101062      0.6817280
5 -0.02986466 -0.002128342 0.02543855 -0.1739012      0.8619431
6  0.33735900 -0.005612861 0.06685225  1.3264793      0.1846810</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">printCoefmat</span>(<span class="fu">data.frame</span>(</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  localMI_amt[fips_amt,], </span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names=</span>Thai_total_for_prov<span class="sc">$</span>ADM1_EN[fips_amt]),</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  Ii        E.Ii      Var.Ii        Z.Ii
Pattani                  -5.7522e-02 -5.7584e-03  6.8575e-02 -1.9767e-01
Ang Thong                 3.3736e-01 -5.6129e-03  6.6852e-02  1.3265e+00
Nong Bua Lam Phu          2.4326e-01 -5.5605e-03  6.6232e-02  9.6684e-01
Chai Nat                  3.1443e-01 -4.6751e-03  5.5735e-02  1.3517e+00
Samut Songkhram          -1.5504e-01 -4.3454e-03  5.1822e-02 -6.6196e-01
Chachoengsao             -4.7882e-01 -4.3028e-03  5.1316e-02 -2.0947e+00
Lamphun                  -2.7324e-02 -4.1016e-03  4.8926e-02 -1.0499e-01
Nong Khai                 2.3278e-01 -4.0705e-03  4.8557e-02  1.0748e+00
Nakhon Phanom             2.3487e-01 -3.9054e-03  4.6596e-02  1.1062e+00
Sing Buri                 2.9178e-01 -3.8246e-03  4.5635e-02  1.3838e+00
Samut Sakhon             -5.9765e-02 -3.7769e-03  4.5068e-02 -2.6373e-01
Suphan Buri               2.7567e-01 -3.7623e-03  4.4895e-02  1.3188e+00
Lop Buri                  2.6605e-01 -3.7262e-03  4.4466e-02  1.2793e+00
Saraburi                  2.5607e-01 -3.6808e-03  4.3925e-02  1.2394e+00
Bueng Kan                 2.4349e-01 -3.6642e-03  4.3728e-02  1.1819e+00
Phichit                   2.1841e-01 -3.6016e-03  4.2984e-02  1.0708e+00
Uttaradit                 1.2484e-01 -3.3648e-03  4.0168e-02  6.3971e-01
Nakhon Sawan              2.5830e-01 -3.3224e-03  3.9663e-02  1.3137e+00
Nakhon Pathom            -5.4433e-02 -3.2806e-03  3.9165e-02 -2.5847e-01
Pathum Thani             -8.4233e-02 -3.2649e-03  3.8979e-02 -4.1011e-01
Maha Sarakham             1.8807e-01 -3.2442e-03  3.8732e-02  9.7212e-01
Kamphaeng Phet            1.8255e-01 -3.1626e-03  3.7761e-02  9.5568e-01
Mukdahan                  2.0915e-01 -3.0974e-03  3.6985e-02  1.1036e+00
Phayao                   -6.6624e-02 -3.0813e-03  3.6793e-02 -3.3127e-01
Nonthaburi               -5.8554e-02 -2.9871e-03  3.5672e-02 -2.9421e-01
Phatthalung              -1.7806e-01 -2.9558e-03  3.5299e-02 -9.3198e-01
Samut Prakan             -2.7854e-01 -2.8886e-03  3.4500e-02 -1.4840e+00
Chaiyaphum                1.9224e-01 -2.8884e-03  3.4497e-02  1.0506e+00
Roi Et                    2.0043e-01 -2.8802e-03  3.4399e-02  1.0962e+00
Ratchaburi               -1.1302e-01 -2.6999e-03  3.2252e-02 -6.1429e-01
Yasothon                  1.6814e-01 -2.5723e-03  3.0731e-02  9.7381e-01
Sa Kaeo                   1.0400e-01 -2.3492e-03  2.8072e-02  6.3471e-01
Surin                     1.6933e-01 -2.2140e-03  2.6460e-02  1.0546e+00
Si Sa Ket                 1.4780e-01 -2.2121e-03  2.6437e-02  9.2258e-01
Uthai Thani               1.8663e-01 -2.1408e-03  2.5587e-02  1.1801e+00
Phra Nakhon Si Ayutthaya -2.9865e-02 -2.1283e-03  2.5439e-02 -1.7390e-01
Sakon Nakhon              1.8025e-01 -2.0560e-03  2.4575e-02  1.1629e+00
Phrae                     1.3037e-01 -1.8907e-03  2.2604e-02  8.7972e-01
Kalasin                   1.5973e-01 -1.8303e-03  2.1883e-02  1.0921e+00
Amnat Charoen             1.4295e-01 -1.7371e-03  2.0771e-02  1.0039e+00
Sukhothai                 1.1311e-01 -1.6607e-03  1.9858e-02  8.1445e-01
Loei                      1.3277e-01 -1.3131e-03  1.5708e-02  1.0699e+00
Buri Ram                  1.1963e-01 -1.1598e-03  1.3876e-02  1.0255e+00
Phetchabun                1.2629e-01 -1.1065e-03  1.3239e-02  1.1072e+00
Khon Kaen                 1.2737e-01 -1.0502e-03  1.2566e-02  1.1456e+00
Nakhon Nayok             -4.6308e-02 -1.0330e-03  1.2361e-02 -4.0723e-01
Phitsanulok               1.1189e-01 -9.6393e-04  1.1535e-02  1.0508e+00
Udon Thani                1.1562e-01 -8.1649e-04  9.7717e-03  1.1778e+00
Nakhon Ratchasima         7.5297e-02 -5.8334e-04  6.9830e-03  9.0805e-01
Nakhon Si Thammarat      -3.5477e-01 -4.7004e-04  5.6274e-03 -4.7230e+00
Ubon Ratchathani          7.8349e-02 -4.3726e-04  5.2351e-03  1.0889e+00
Tak                       8.4558e-02 -4.2203e-04  5.0528e-03  1.1955e+00
Prachin Buri             -3.3085e-03 -2.9059e-04  3.4796e-03 -5.1161e-02
Yala                      3.0558e-04 -2.0620e-04  2.4694e-03  1.0299e-02
Narathiwat                4.1699e-04 -1.8560e-04  2.2226e-03  1.2782e-02
Kanchanaburi              5.9377e-02 -1.6943e-04  2.0290e-03  1.3220e+00
Lampang                   1.8328e-02 -9.6259e-05  1.1529e-03  5.4264e-01
Nan                       1.1167e-02 -7.3659e-05  8.8221e-04  3.7845e-01
Satun                     1.6107e-03 -6.0923e-05  7.2968e-04  6.1884e-02
Chanthaburi               1.5947e-02 -1.2956e-05  1.5518e-04  1.2812e+00
Chumphon                  1.4525e-01 -2.5567e-04  3.0616e-03  2.6297e+00
Ranong                    3.4008e-01 -4.4125e-04  5.2829e-03  4.6850e+00
Mae Hong Son              1.7977e-02 -1.1533e-03  1.3798e-02  1.6286e-01
Rayong                    1.5457e-01 -1.5642e-03  1.8706e-02  1.1416e+00
Phetchaburi              -1.2082e-01 -2.5696e-03  3.0699e-02 -6.7490e-01
Trang                     7.0102e-01 -3.8950e-03  4.6472e-02  3.2699e+00
Songkhla                 -1.1497e-01 -7.6719e-03  9.1187e-02 -3.5533e-01
Chiang Rai               -8.5294e-02 -1.0065e-02  1.1935e-01 -2.1776e-01
Prachuap Khiri Khan      -2.1731e-01 -1.0630e-02  1.2597e-01 -5.8233e-01
Chiang Mai               -5.5832e-02 -1.3067e-02  1.5447e-01 -1.0881e-01
Phangnga                  2.0359e+00 -1.7556e-02  2.0659e-01  4.5178e+00
Trat                      3.9271e-01 -2.6245e-02  3.0610e-01  7.5723e-01
Krabi                     2.8622e+00 -4.5766e-02  5.2308e-01  4.0207e+00
Surat Thani               3.5031e+00 -7.1979e-02  8.0009e-01  3.9969e+00
Chon Buri                 9.4504e-01 -7.8029e-02  8.6168e-01  1.1021e+00
Bangkok                  -1.5080e+00 -1.2984e-01  1.3533e+00 -1.1847e+00
Phuket                    5.0943e+00 -4.4770e-01  2.9617e+00  3.2203e+00
                         Pr.z....E.Ii..
Pattani                          0.8433
Ang Thong                        0.1847
Nong Bua Lam Phu                 0.3336
Chai Nat                         0.1765
Samut Songkhram                  0.5080
Chachoengsao                     0.0362
Lamphun                          0.9164
Nong Khai                        0.2825
Nakhon Phanom                    0.2687
Sing Buri                        0.1664
Samut Sakhon                     0.7920
Suphan Buri                      0.1872
Lop Buri                         0.2008
Saraburi                         0.2152
Bueng Kan                        0.2372
Phichit                          0.2842
Uttaradit                        0.5224
Nakhon Sawan                     0.1890
Nakhon Pathom                    0.7960
Pathum Thani                     0.6817
Maha Sarakham                    0.3310
Kamphaeng Phet                   0.3392
Mukdahan                         0.2698
Phayao                           0.7404
Nonthaburi                       0.7686
Phatthalung                      0.3513
Samut Prakan                     0.1378
Chaiyaphum                       0.2934
Roi Et                           0.2730
Ratchaburi                       0.5390
Yasothon                         0.3302
Sa Kaeo                          0.5256
Surin                            0.2916
Si Sa Ket                        0.3562
Uthai Thani                      0.2379
Phra Nakhon Si Ayutthaya         0.8619
Sakon Nakhon                     0.2449
Phrae                            0.3790
Kalasin                          0.2748
Amnat Charoen                    0.3154
Sukhothai                        0.4154
Loei                             0.2847
Buri Ram                         0.3052
Phetchabun                       0.2682
Khon Kaen                        0.2520
Nakhon Nayok                     0.6838
Phitsanulok                      0.2934
Udon Thani                       0.2389
Nakhon Ratchasima                0.3639
Nakhon Si Thammarat              0.0000
Ubon Ratchathani                 0.2762
Tak                              0.2319
Prachin Buri                     0.9592
Yala                             0.9918
Narathiwat                       0.9898
Kanchanaburi                     0.1862
Lampang                          0.5874
Nan                              0.7051
Satun                            0.9507
Chanthaburi                      0.2001
Chumphon                         0.0085
Ranong                           0.0000
Mae Hong Son                     0.8706
Rayong                           0.2536
Phetchaburi                      0.4997
Trang                            0.0011
Songkhla                         0.7223
Chiang Rai                       0.8276
Prachuap Khiri Khan              0.5603
Chiang Mai                       0.9134
Phangnga                         0.0000
Trat                             0.4489
Krabi                            0.0001
Surat Thani                      0.0001
Chon Buri                        0.2704
Bangkok                          0.2361
Phuket                           0.0013</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov.localMI_amt <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Thai_total_for_prov,localMI_amt) <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Pr.Ii =</span> Pr.z....E.Ii..)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>map_localMI_amt_Ii <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov.localMI_amt) <span class="sc">+</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Ii"</span>, </span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"RdBu"</span>,</span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local moran statistics"</span>) <span class="sc">+</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb99-7"><a href="#cb99-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-8"><a href="#cb99-8" aria-hidden="true" tabindex="-1"></a>map_localMI_amt_P <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov.localMI_amt) <span class="sc">+</span></span>
<span id="cb99-9"><a href="#cb99-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"Pr.Ii"</span>, </span>
<span id="cb99-10"><a href="#cb99-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb99-11"><a href="#cb99-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>, </span>
<span id="cb99-12"><a href="#cb99-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span></span>
<span id="cb99-13"><a href="#cb99-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb99-14"><a href="#cb99-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-15"><a href="#cb99-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-16"><a href="#cb99-16" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map_localMI_amt_Ii, </span>
<span id="cb99-17"><a href="#cb99-17" aria-hidden="true" tabindex="-1"></a>             map_localMI_amt_P , </span>
<span id="cb99-18"><a href="#cb99-18" aria-hidden="true" tabindex="-1"></a>             <span class="at">asp=</span><span class="dv">1</span>, </span>
<span id="cb99-19"><a href="#cb99-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>Based on the generated outputs, the we have noted that there are two areas of interest. The region at the gulf of Thailand, is of a higher Local Moran Statistic and is statistically significant. This is not un expected as the region is home the exclusive beach resorts which likely indicative of higher spending power.</p>
<p>It is observed that the Mae Hong Son and the Prachinbur seems to be outliner, This is not surprising as they are not popular tourists town for foreign tourist.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>nci <span class="ot">&lt;-</span> <span class="fu">moran.plot</span>(Thai_total_for_prov<span class="sc">$</span>lag.Amt_rev_per_for_tourist, rswm_knn6,</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels=</span><span class="fu">as.character</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN), </span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">xlab=</span><span class="st">"Amt of Revenue per foreign tourists"</span>, </span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">ylab=</span><span class="st">"Spatially Lag Amt of Revenue per foreign tourists"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on the above graph, there are 4 quarters</p>
<p>“High-High” - Top right corner : Positive Autocorrelation Cluster. Provinces here have high percentage of higher amount of revenue per foreign tourist surrounded by other provinces with high amount of foreign spending. It is noted that these provinces are located in southern Thailand near to the gulf of Thailand which of exclusive beach resorts.</p>
<p>“Low-High” - Top left corner: Negative Autocorrelation Cluster. Provinces here have low amount of revenue per foreign tourist surrounded by other provinces with high amount of revenue per foreign tourists.</p>
<p>“High-Low” - Bottom right corner: Negative Autocorrelation Cluster. Provinces here have high amount of revenue per foreign tourist surrounded by other provinces with low amount of revenue per foreign tourists. It is noted that Bangkok is in this region.</p>
<p>“Low-Low” - Bottom left corner : Positive Autocorrelation Cluster. Provinces here have low amount of revenue per foreign tourist surrounded by other provinces with low amount of revenue per foreign tourists</p>
</section>
</section>
<section id="lisa-map" class="level3">
<h3 class="anchored" data-anchor-id="lisa-map">Lisa Map:</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 1</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>quadrant <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">mode=</span><span class="st">"numeric"</span>,<span class="at">length=</span><span class="fu">nrow</span>(localMI_amt))</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 2</span></span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov<span class="sc">$</span>lag_Amt_rev_per_for_tourist <span class="ot">&lt;-</span> <span class="fu">lag.listw</span>(rswm_knn6, Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist)</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>DV <span class="ot">&lt;-</span> Thai_total_for_prov<span class="sc">$</span>lag_Amt_rev_per_for_tourist <span class="sc">-</span> <span class="fu">mean</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist)     </span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 3</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>LM_I <span class="ot">&lt;-</span> localMI_amt[,<span class="dv">1</span>]</span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 4</span></span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>signif <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-13"><a href="#cb101-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 5</span></span>
<span id="cb101-14"><a href="#cb101-14" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co">#low-low</span></span>
<span id="cb101-15"><a href="#cb101-15" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="co">#high-low</span></span>
<span id="cb101-16"><a href="#cb101-16" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&lt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&lt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="co">#low-high</span></span>
<span id="cb101-17"><a href="#cb101-17" aria-hidden="true" tabindex="-1"></a>quadrant[DV <span class="sc">&gt;</span><span class="dv">0</span> <span class="sc">&amp;</span> LM_I<span class="sc">&gt;</span><span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="dv">4</span> <span class="co">#high-high</span></span>
<span id="cb101-18"><a href="#cb101-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-19"><a href="#cb101-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 6</span></span>
<span id="cb101-20"><a href="#cb101-20" aria-hidden="true" tabindex="-1"></a>quadrant[localMI_amt[,<span class="dv">5</span>]<span class="sc">&gt;</span>signif]<span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov.localMI_amt<span class="sc">$</span>quadrant <span class="ot">&lt;-</span> quadrant</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#ffffff"</span>, <span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>)</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>clusters <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"insignificant"</span>, <span class="st">"low-low"</span>, <span class="st">"low-high"</span>, <span class="st">"high-low"</span>, <span class="st">"high-high"</span>)</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>LISAmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(Thai_total_for_prov.localMI_amt) <span class="sc">+</span></span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"quadrant"</span>, </span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"cat"</span>, </span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> colors[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>], </span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> clusters[<span class="fu">c</span>(<span class="fu">sort</span>(<span class="fu">unique</span>(quadrant)))<span class="sc">+</span><span class="dv">1</span>],</span>
<span id="cb102-10"><a href="#cb102-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">popup.vars =</span> <span class="fu">c</span>(<span class="st">""</span>)) <span class="sc">+</span></span>
<span id="cb102-11"><a href="#cb102-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">11</span>,<span class="dv">17</span>)) <span class="sc">+</span></span>
<span id="cb102-12"><a href="#cb102-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha=</span><span class="fl">0.5</span>)</span>
<span id="cb102-13"><a href="#cb102-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-14"><a href="#cb102-14" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(amt, LISAmap, </span>
<span id="cb102-15"><a href="#cb102-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also include the local Moran’s I map and p-value map as shown below for easy comparison.</p>
<p>As per Moran scatter plot, we noted thet region of southern thailand are in the high-high quarter, this could be due to the high concentration of island beach resorts in the provinces.</p>
</section>
</section>
<section id="hot-spot-area-analysis" class="level2">
<h2 class="anchored" data-anchor-id="hot-spot-area-analysis">Hot Spot Area Analysis</h2>
<p>Next we will be doing hot spot analysis. AS per earlier discussion, we will using the spatial weights generated using the adaptive distance matrix to detect hot or cold spots. Hot spot is defined as the areas with high values related to its surroundings area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>knn_lw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(knn6,</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">style =</span> <span class="st">"B"</span>,</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>knn_lw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 77 
Number of nonzero links: 462 
Percentage nonzero weights: 7.792208 
Average number of links: 6 
Non-symmetric neighbours list

Weights style: B 
Weights constants summary:
   n   nn  S0  S1    S2
B 77 5929 462 820 11500</code></pre>
</div>
</div>
</section>
<section id="gi-statistics-using-fixed-distance" class="level2">
<h2 class="anchored" data-anchor-id="gi-statistics-using-fixed-distance">Gi statistics using fixed distance</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>gi.fixed <span class="ot">&lt;-</span> <span class="fu">localG</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist, knn_lw)</span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>gi.fixed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] -1.18473998  1.48404987  0.29420505  0.41010622  0.17390119 -1.32647934
 [7] -1.27934010 -1.38376421 -1.35166988 -1.23937666  1.10212995  1.14159542
[13]  1.28121670  0.75723394  2.09472651  0.05116116  0.40723063 -0.63471467
[19] -0.90804750 -1.02545101 -1.05459249 -0.92258216 -1.08890353 -0.97380932
[25] -1.05059129 -1.00389814 -1.18191680 -0.96684035 -1.14562456 -1.17784735
[31] -1.06985642 -1.07482494 -0.97212150 -1.09619761 -1.09211954 -1.16292219
[37] -1.10615455 -1.10363323 -0.10880880  0.10498879 -0.54264019 -0.63970646
[43] -0.87972323 -0.37844539  0.33126759 -0.21775793  0.16286007 -1.31365312
[49] -1.18014002 -0.95567687 -1.19550505 -0.81444879 -1.05077077 -1.07082845
[55] -1.10720235  0.61428937 -1.32195334 -1.31881137  0.25847261  0.26373250
[61]  0.66195565 -0.67489605 -0.58233411  4.72299342  4.02072702  4.51783877
[67]  3.22032996  3.99689410  4.68498447  2.62965812 -0.35533392 -0.06188359
[73]  3.26993568  0.93197932  0.19766965 -0.01029898 -0.01278158
attr(,"internals")
              Gi      E(Gi)        V(Gi)       Z(Gi) Pr(z != E(Gi))
 [1,] 0.03514776 0.07894737 0.0013667667 -1.18473998   2.361203e-01
 [2,] 0.13435075 0.07894737 0.0013937199  1.48404987   1.377957e-01
 [3,] 0.08992889 0.07894737 0.0013932360  0.29420505   7.686012e-01
 [4,] 0.09424769 0.07894737 0.0013919010  0.41010622   6.817280e-01
 [5,] 0.08544879 0.07894737 0.0013976928  0.17390119   8.619431e-01
 [6,] 0.02963705 0.07894737 0.0013818934 -1.32647934   1.846810e-01
 [7,] 0.03125401 0.07894737 0.0013897726 -1.27934010   2.007773e-01
 [8,] 0.02736931 0.07894737 0.0013893314 -1.38376421   1.664307e-01
 [9,] 0.02863201 0.07894737 0.0013856701 -1.35166988   1.764809e-01
[10,] 0.03274042 0.07894737 0.0013899779 -1.23937666   2.152060e-01
[11,] 0.12040136 0.07894737 0.0014147089  1.10212995   2.704052e-01
[12,] 0.12214581 0.07894737 0.0014318969  1.14159542   2.536222e-01
[13,] 0.12722622 0.07894737 0.0014199358  1.28121670   2.001176e-01
[14,] 0.10773361 0.07894737 0.0014451395  0.75723394   4.489097e-01
[15,] 0.15696690 0.07894737 0.0013872412  2.09472651   3.619531e-02
[16,] 0.08086948 0.07894737 0.0014114920  0.05116116   9.591971e-01
[17,] 0.09420959 0.07894737 0.0014046063  0.40723063   6.838386e-01
[18,] 0.05522831 0.07894737 0.0013964903 -0.63471467   5.256145e-01
[19,] 0.04487048 0.07894737 0.0014083248 -0.90804750   3.638531e-01
[20,] 0.04052797 0.07894737 0.0014036900 -1.02545101   3.051504e-01
[21,] 0.03952731 0.07894737 0.0013972212 -1.05459249   2.916117e-01
[22,] 0.04446165 0.07894737 0.0013972315 -0.92258216   3.562250e-01
[23,] 0.03806218 0.07894737 0.0014097861 -1.08890353   2.761964e-01
[24,] 0.04257174 0.07894737 0.0013953182 -0.97380932   3.301512e-01
[25,] 0.03972609 0.07894737 0.0013937210 -1.05059129   2.934463e-01
[26,] 0.04138563 0.07894737 0.0013999487 -1.00389814   3.154277e-01
[27,] 0.03488147 0.07894737 0.0013900533 -1.18191680   2.372387e-01
[28,] 0.04300355 0.07894737 0.0013820984 -0.96684035   3.336238e-01
[29,] 0.03601350 0.07894737 0.0014044793 -1.14562456   2.519505e-01
[30,] 0.03477751 0.07894737 0.0014062871 -1.17784735   2.388575e-01
[31,] 0.03887935 0.07894737 0.0014026349 -1.06985642   2.846839e-01
[32,] 0.03890029 0.07894737 0.0013882455 -1.07482494   2.824531e-01
[33,] 0.04267800 0.07894737 0.0013919992 -0.97212150   3.309901e-01
[34,] 0.03802289 0.07894737 0.0013937619 -1.09619761   2.729923e-01
[35,] 0.03809283 0.07894737 0.0013993949 -1.09211954   2.747806e-01
[36,] 0.03546439 0.07894737 0.0013980971 -1.16292219   2.448611e-01
[37,] 0.03772219 0.07894737 0.0013889717 -1.10615455   2.686596e-01
[38,] 0.03776098 0.07894737 0.0013927010 -1.10363323   2.697523e-01
[39,] 0.07481092 0.07894737 0.0014451955 -0.10880880   9.133541e-01
[40,] 0.08285897 0.07894737 0.0013881100  0.10498879   9.163847e-01
[41,] 0.05853818 0.07894737 0.0014145801 -0.54264019   5.873776e-01
[42,] 0.05508511 0.07894737 0.0013914313 -0.63970646   5.223635e-01
[43,] 0.04604241 0.07894737 0.0013990416 -0.87972323   3.790093e-01
[44,] 0.06471113 0.07894737 0.0014150907 -0.37844539   7.050998e-01
[45,] 0.09131026 0.07894737 0.0013927786  0.33126759   7.404424e-01
[46,] 0.07067277 0.07894737 0.0014439292 -0.21775793   8.276177e-01
[47,] 0.08510656 0.07894737 0.0014302692  0.16286007   8.706286e-01
[48,] 0.02994212 0.07894737 0.0013916300 -1.31365312   1.889630e-01
[49,] 0.03482806 0.07894737 0.0013976237 -1.18014002   2.379445e-01
[50,] 0.04328656 0.07894737 0.0013923877 -0.95567687   3.392355e-01
[51,] 0.03405699 0.07894737 0.0014099500 -1.19550505   2.318898e-01
[52,] 0.04846900 0.07894737 0.0014004120 -0.81444879   4.153879e-01
[53,] 0.03955923 0.07894737 0.0014051252 -1.05077077   2.933639e-01
[54,] 0.03901914 0.07894737 0.0013903377 -1.07082845   2.842466e-01
[55,] 0.03745948 0.07894737 0.0014040699 -1.10720235   2.682065e-01
[56,] 0.10188814 0.07894737 0.0013946651  0.61428937   5.390241e-01
[57,] 0.02925126 0.07894737 0.0014132292 -1.32195334   1.861837e-01
[58,] 0.02978541 0.07894737 0.0013896103 -1.31881137   1.872322e-01
[59,] 0.08859026 0.07894737 0.0013918272  0.25847261   7.960422e-01
[60,] 0.08877842 0.07894737 0.0013895449  0.26373250   7.919861e-01
[61,] 0.10360074 0.07894737 0.0013870589  0.66195565   5.079996e-01
[62,] 0.05338241 0.07894737 0.0014348832 -0.67489605   4.997418e-01
[63,] 0.05681694 0.07894737 0.0014442260 -0.58233411   5.603417e-01
[64,] 0.25626049 0.07894737 0.0014094416  4.72299342   2.323984e-06
[65,] 0.23137140 0.07894737 0.0014371356  4.02072702   5.801881e-05
[66,] 0.25074287 0.07894737 0.0014459794  4.51783877   6.247402e-06
[67,] 0.17824410 0.07894737 0.0009507561  3.22032996   1.280431e-03
[68,] 0.22953495 0.07894737 0.0014194922  3.99689410   6.417899e-05
[69,] 0.25587404 0.07894737 0.0014261668  4.68498447   2.799812e-06
[70,] 0.17819581 0.07894737 0.0014244552  2.62965812   8.547078e-03
[71,] 0.06545272 0.07894737 0.0014422801 -0.35533392   7.223394e-01
[72,] 0.07661919 0.07894737 0.0014154116 -0.06188359   9.506555e-01
[73,] 0.20293142 0.07894737 0.0014376501  3.26993568   1.075719e-03
[74,] 0.11373641 0.07894737 0.0013933894  0.93197932   3.513472e-01
[75,] 0.08629400 0.07894737 0.0013813275  0.19766965   8.433035e-01
[76,] 0.07856028 0.07894737 0.0014126548 -0.01029898   9.917827e-01
[77,] 0.07846692 0.07894737 0.0014129703 -0.01278158   9.898020e-01
attr(,"cluster")
 [1] High Low  Low  Low  Low  Low  Low  Low  Low  Low  High High High High Low 
[16] Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low 
[31] Low  Low  Low  Low  Low  Low  Low  Low  High Low  Low  Low  Low  Low  Low 
[46] High High Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low  Low 
[61] Low  High High Low  High High High High High High High Low  High Low  Low 
[76] Low  Low 
Levels: Low High
attr(,"gstari")
[1] FALSE
attr(,"call")
localG(x = Thai_total_for_prov$Amt_rev_per_for_tourist, listw = knn_lw)
attr(,"class")
[1] "localG"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>Thai_total_for_prov.gi <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Thai_total_for_prov, <span class="fu">as.matrix</span>(gi.fixed)) <span class="sc">%&gt;%</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_fixed =</span> as.matrix.gi.fixed.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>Gimap <span class="ot">&lt;-</span><span class="fu">tm_shape</span>(Thai_total_for_prov.gi) <span class="sc">+</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_fixed"</span>, </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>,</span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Gi"</span>) <span class="sc">+</span></span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb108-7"><a href="#cb108-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Total_rev, Gimap, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="observations" class="level4">
<h4 class="anchored" data-anchor-id="observations">observations</h4>
<p>Based on generated maps, the hot-spots are located the province having islands eg. Phunket, Krabi, Trang where beach resorts are located. The cold spots are located at north east Thailand near the border with Laos ### Gi statistics using adaptive distance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>fips <span class="ot">&lt;-</span> <span class="fu">order</span>(Thai_total_for_prov<span class="sc">$</span>ADM1_EN)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>gi.adaptive <span class="ot">&lt;-</span> <span class="fu">localG</span>(Thai_total_for_prov<span class="sc">$</span>Amt_rev_per_for_tourist, knn_lw)</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>Thai_total_for_pro_adp.gi <span class="ot">&lt;-</span> <span class="fu">cbind</span>(Thai_total_for_prov, <span class="fu">as.matrix</span>(gi.adaptive)) <span class="sc">%&gt;%</span></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">gstat_adaptive =</span> as.matrix.gi.adaptive.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>Gimap_adap <span class="ot">&lt;-</span><span class="fu">tm_shape</span>(Thai_total_for_pro_adp.gi) <span class="sc">+</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"gstat_adaptive"</span>, </span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"pretty"</span>,</span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette=</span><span class="st">"-RdBu"</span>,</span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"local Gi"</span>) <span class="sc">+</span></span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb110-7"><a href="#cb110-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-8"><a href="#cb110-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(Gimap_adap, Gimap, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="observations-1" class="level4">
<h4 class="anchored" data-anchor-id="observations-1">observations</h4>
<p>Based on the above maps, it is noted that the Gi statistic calculated by fixed distance or adaptive distance is the same. Hence the observation made for Local Gi derived by fixed method is valid.</p>
</section>
</section>
<section id="time-series" class="level2">
<h2 class="anchored" data-anchor-id="time-series">Time Series</h2>
<p>In this section, we will be doing spatial temporal analysis tourism data. We will be using the total revenue generated from foreign tourists. We use this indicator instead of the amount of the revenue spent per foreign tourists as it will be able to provide more Representative of more region of Thailand and it is readily available in the raw data. By using a more general indicator, it will help us to understand the changes in all regions and also to be able to capture a border based instead of just focusing on the</p>
<p>We will start of with preparing the timecube data and ensuring that it is in spacetime.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a> Tourdata_st <span class="ot">&lt;-</span> <span class="fu">spacetime</span>(tour_data_wide, SAB_1,</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">.loc_col =</span> <span class="st">"ADM1_EN"</span>,</span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">.time_col =</span> <span class="st">"Date_tour"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is_spacetime_cube</span>(Tourdata_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<section id="emerging-hotpots" class="level3">
<h3 class="anchored" data-anchor-id="emerging-hotpots">Emerging Hotpots</h3>
<p>After ensuring that the data is in correct format,the following code is used to run the emerging hot spot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span> <span class="fu">emerging_hotspot_analysis</span>(</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> Tourdata_st, </span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">.var =</span> <span class="st">"revenue_foreign"</span>, </span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">k =</span> <span class="dv">1</span>, </span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">nsim =</span> <span class="dv">99</span></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(ehsa ,<span class="st">"data/rds/ehsa.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/ehsa.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>Thai_ehsa <span class="ot">&lt;-</span> SAB_1 <span class="sc">%&gt;%</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(ehsa,</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">by =</span> <span class="fu">join_by</span>(ADM1_EN<span class="sc">==</span> location))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(Thai_ehsa ,<span class="st">"data/rds/Thai_ehsa.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>Thai_ehsa<span class="ot">&lt;-</span><span class="fu">read_rds</span>(<span class="st">"data/rds/Thai_ehsa.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>ehsa_sig <span class="ot">&lt;-</span> Thai_ehsa  <span class="sc">%&gt;%</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(Thai_ehsa) <span class="sc">+</span></span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb120-7"><a href="#cb120-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ehsa_sig) <span class="sc">+</span></span>
<span id="cb120-8"><a href="#cb120-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"classification"</span>) <span class="sc">+</span> </span>
<span id="cb120-9"><a href="#cb120-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take_home_02_files/figure-html/unnamed-chunk-80-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions:</h2>
<p>Based on the local Moran results, using the indicator: Amount of revenue per Foreign Tourists, there are some spatial correlation of the tourist hot-spot at the region near to the gulf of Thailand eg. Phunket and Krabi which are home to the exclusive beach resorts. Other that regions mentioned, other spatial correlation is not observed.</p>
<p>However it is noted the amount of revenue per foreign tourist is a very narrow indicator. Bangkok for example, has very high revenue but also very high number of foreign tourists leading to it being not in the top 5 provinces.</p>
<p>Hence during the spatial temporal analysis, a more general indicator revenue from foreign tourists is used to analyse if there are any emerging hot-spots or cold spots.</p>
<p>From the generated map for the emerging hotspot, there are no consecutive hot-spots or cold-spots. There is only one sporadic hot-spot at the province of Ang Thong. Based on Wikipedia, it has more than 200 Buddhist Temples. The definition of the sporadic hot-spot is the final time step interval with history of on and off with more than 90 of the time interval being a statistically significant hotspot. This maybe due to religious activities.</p>
<p>For sporadic cold spots, there are provinces which has a history of being a statistically significant cold spot during a prior time steps. They are Yala, Chumphon, Chanthaburi, Sa Kaew, Mukdahan, Loei, Chainat, kamphaeng-Phet, Lamphun.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>